### ISSUE TITLE
Can this handle more than 1 sequence at a time?

### ISSUE THREAD

**Issue by veravelasco** [draeger-lab/TFpredict#2]
I am wondering if this can handle a fasta file with more than 1 sequence?  Or perhaps there is a limit? Maybe 20,000 cds?  I have been trying to use this software with my transcriptome and it keeps running but no output is created.   It does not have a problem with the provided test fasta which has 1 sequence.  
Thanks.

**Comment by draeger** [comment]
In `batchMode` the variable `maxNumSequencesBatchMode = 10`.

The sequence for `transcript3508.p1_2_1` is being checked using regular expressions and the warning is because of the asterisk `*`:
```
if (!seq.matches("^[A-IK-NP-Za-ik-np-z\\s]*$")) {
  System.out.println("\nWarning. Given protein sequence \"" + header + "\" contains invalid symbols.");
}
```
