### ISSUE TITLE
0 InterPro domain(s) found.

### ISSUE THREAD

**Issue by NailouZhang** [draeger-lab/TFpredict#4]
hello,
I work TFpredict with interproscan-5.52-86.0 and latest blast in conda environment, with followed commands;
java -jar ~/Softwares/Miniconda3/DeepTFactor/TFpredict/dist/TFpredict_1.3.jar \
    test_seq.fasta \
    -sabineOutfile example.output \
    -species "Homo sapiens"\
    -iprscanPath /home/stone/Softwares/Miniconda3/miniconda3/envs/interproscan/bin/interproscan.sh \
    -blastPath /home/stone/Softwares/Miniconda3/miniconda3/envs/interproscan/

# However, there is no  InterPro domain(s) found.

The Softwares output as follow:
-----------------------------------------------------------------------
TFpredict
Identification and structural characterization of transcription factors
-----------------------------------------------------------------------
(version 1.3)

Copyright (C) 2012 Center for Bioinformatics Tuebingen (ZBIT),
University of Tuebingen, Florian Topf and Johannes Eichner.

This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain
conditions.
For details see: http://www.gnu.org/licenses/gpl-3.0.html

Third-party software used by this program:
  WEKA. Copyright (C) 1998, 1999 Eibe Frank, Leonard Trigg, Mark Hall.
  All rights reserved.
  InterProScan. Copyright (C) 2011 Sarah Hunter, EMBL-EBI. All rights reserved.

  Input FASTA file:       test_seq.fasta
  SABINE output file:     example.output
  Organism:               Homo sapiens
  TF/non-TF classifier:   SVM linear kernel
  Superclass classifier:  SVM linear kernel

- Fetching domains from InterProScan. This may take several minutes... 

Processed Sequence1:
  0 InterPro domain(s) found.
  0 / 0 InterPro domain(s) are relevant for TF/Non-TF classification.
  0 / 0 InterPro domain(s) are relevant for Superclass prediction.
  0 / 0 InterPro domain(s) were identified as DNA-binding domain(s).

==========================================
Results report for sequence: Sequence1
==========================================

  TF/Non-TF prediction:
  -----------------------
                Probability
  TF            1.00
  Non-TF        0.00

  Superclass prediction:
  -----------------------
                      Probability
  Basic domain        0.00
  Zinc finger         0.00
  Helix-turn-helix    0.00
  Beta scaffold       1.00
  Other               0.00

  DNA-binding domain could not be predicted.

# So, Could you please help me resolve this problem, Is interproscan-5.52-86.0 not the right version or any others?

**Comment by papelypluma** [comment]
Hi @NailouZhang. By any chance, were you able to find a solution to this issue? I've just encountered this exact same issue with TFpredict. Could it be due to the InterProScan? Thank you.

**Comment by dorimolnar** [comment]
Thanks for reaching out. We were unable to reproduce the issue you described. It appears to be related to the specific version of InterProScan you're using. We recommend using the latest InterProScan web service, as it consistently provides up-to-date results and is more efficient in terms of memory usage. This should help ensure that TFpredict functions as expected.

For test_seq.fasta the correct result with the webservice version: 

Processed Sequence1:
  9 InterPro domain(s) found.
  6 / 9 InterPro domain(s) are relevant for TF/Non-TF classification.
  6 / 9 InterPro domain(s) are relevant for Superclass prediction.
  0 / 9 InterPro domain(s) were identified as DNA-binding domain(s).
